version: '3.2'
# Port: 25565 Game client connect
# Port: 25575 RCON remote CLI port
# UID 99 is nobody
# Download server files at: https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/files
services:
  # ITZG Minecraft Docs: https://github.com/itzg/docker-minecraft-server/blob/master/README.md
  mc:
    container_name: $DOCKER_NAME
    # https://github.com/itzg/docker-minecraft-server/blob/master/README.md#running-minecraft-server-on-different-java-version
    # Forge versions <= 1.17 requires java8, for newer modpacks, use :latest (Java 17)
    image: itzg/minecraft-server:java8
    restart: always
    volumes:
    - ./modpacks:/modpacks:ro
    - ./data:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    environment:
      INIT_MEMORY: 2G
      MAX_MEMORY: 8G
      JVM_DD_OPTS: "docker=${DOCKER_NAME}"

      # This AUTO_PAUSE pauses the process so it takes no CPU, but it still takes Memory, and it fails to startup on connecting.
      MAX_TICK_TIME: "-1" # To prevent watchdog to restart server after it unpauses due to long tick
      # Auto-stops java-process when no one connected and restarts on connection. May need to disable watch or disable tick-counter. See docs
      # pauses the process, does not stop the docker, and the docker looks like its running (as its up), but it does not answer login. So disable.
      ENABLE_AUTOPAUSE: "false"
      AUTOPAUSE_TIMEOUT_EST: "60" # default 3600 (seconds) describes the time between the last client disconnect and the pausing of the process (read as timeout established)
      # AUTOPAUSE_TIMEOUT_INIT: "600" # default 600 (seconds) describes the time between server start and the pausing of the process, when no client connects inbetween (read as timeout initialized)
      # AUTOPAUSE_TIMEOUT_KN: "1800" # default 120 (seconds) describes the time between knocking of the port (e.g. by the main menu ping) and the pausing of the process, when no client connects inbetween (read as timeout knocked)
      # AUTOPAUSE_PERIOD: "10" # default 10 (seconds) describes period of the daemonized state machine, that handles the pausing of the process (resuming is done independently)
      # AUTOPAUSE_KNOCK_INTERFACE: "eth0" # default eth0, Describes the interface passed to the knockd daemon. If the default interface does not work, run the ifconfig command inside the container and derive the interface receiving the incoming connection from its output. The passed interface must exist inside the container. Using the loopback interface (lo) does likely not yield the desired results.
      
      # Forge options
      #  VERSION: "1.12.2"
      #  TYPE: FORGE
      #  FORGEVERSION: "14.23.5.2847"

      # CurseForge options using downloaded server-files.zip
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/SIMPLE-SERVER-FILES-1.8.7.zip

      ALLOW_FLIGHT: "true"
      ALLOW_NETHER: "true"
      ENABLE_COMMAND_BLOCK: "true"
      EULA: "true"
      FORCE_GAMEMODE: "false" # false - Players will join in the gamemode they left in.
      GUI: "false"
      MODE: "creative"
      MOTD: "All the mods"
      ONLINE_MODE: "true"
      OPS: "QuirkySpirit,LunaKittyCatty,Magicilly,Mr_Duckv2"

      UID: 99
      GID: 100
    ports:
      - "$PORT:25565"
      - "$PORT_RCON:25575"
