version: '3.2'
# Port: 25565 Game client connect
# Port: 25575 RCON remote CLI port
# UID 99 is nobody
# Download server files at: https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/files
services:
  mc:
    container_name: $DOCKER_NAME
    image: itzg/minecraft-bedrock-server:latest
    restart: always
    volumes:
    - ./data:/data
    # - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    environment:
      # See https://hub.docker.com/r/itzg/minecraft-bedrock-server
      # OPS: "QuirkySpirit,LunaKittyCatty,Magicilly,Mr_Duckv2"
      # Latest version may not be available in Play store yet.
      VERSION: $BEDROCK_VERSION
      ONLINE_MODE: "true"
      GAMEMODE: "creative"
      DIFFICULTY: "normal"
      WHITE_LIST_USERS: "QuirkySpirit,LunaKittyCatty,Magicilly,Mr_Duckv2,CrackyAppy,ShoppyDoppy,MBBeyblade"
      GUI: "false"
      EULA: "true"
      UID: 99
      GID: 100
    ports:      
      - 19132:19132/udp
